# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Companion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Companion
    pod 'Alamofire', '~> 4.7'
    pod 'SCLAlertView'
    pod 'NVActivityIndicatorView'
    pod 'BiometricAuthentication'
    pod 'KeychainSwift', '~> 11.0'
    pod 'SwiftyJSON'
    pod 'DropDown'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftyGif'
    pod 'lottie-ios'
    pod 'SwiftyMenu', '~> 1.0.1'
    pod 'SelectionList'
    pod 'DatePickerDialog'
    pod 'NotificationBannerSwift', '~> 3.0.0'
    pod 'JitsiMeetSDK', '5.1.0'
    
    pod 'Socket.IO-Client-Swift', '~> 15.2.0'
#    pod 'ChatViewController'
    pod 'Kingfisher'
    pod 'PlaceholderUITextView'
    pod 'Firebase'
    pod 'Firebase/Messaging'

end
